function getArticles() {
    return [
        {
            title: 'Dark Brazilian Santos',
            describtione: 'Brazil is known the world over as one of the most prolific and dedicated of coffee producers. This Brazilian Santos coffee is roasted to the French level. It produces a rich, full-bodied flavor yet maintains the smoothness usually found in a lighter roast. Featuring delicate notes of cinnamon and undertones of dark chocolate, this bean is perfect for anything from drip coffee to espresso. Rich in flavor yet delicate and low in acidity, this coffee can please all palates. Tasting notes: Chocolate, Nut.',
            price: 19.95,
            image1: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/d/a/dark-brazilian-santos-2021-square.jpg',
            image2: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/d/a/dark-brazilian-santos-bag-2021-square.jpg',
            image3: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/d/a/dark-brazilian-santos-2021-square.jpg',
            image4: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/d/a/dark-brazilian-santos-bag-2021-square.jpg',
        },
        {
            title: 'Colombian Supremo',
            describtione: 'This coffee is what off-the-shelf brands are trying to emulate when they offer “100% Colombian” blends, but not one of them comes close to the quality of our fresh roasted Colombian Supremo beans. This classic artisan coffee is light roasted and displays a smooth yet complex body and a bright, sunny acidity. These large beans feature undertones of juicy lemons, brown sugar, and milk chocolate. If you are new to buying freshly roasted coffee and don`t know where to begin, or if you`re a veteran, this selection will satisfy your coffee craving! Tasting notes: Citrus, Berry, Chocolate.',
            price: 19.95,
            image1: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/b/r/breakfast-blend-2021-square.jpg',
            image2: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/c/o/colombian-supremo-bag-2021-square.jpg',
            image3: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/b/r/breakfast-blend-2021-square.jpg',
            image4: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/c/o/colombian-supremo-bag-2021-square.jpg',
        },
        {
            title: 'Decaf Dark Sumatra',
            describtione: 'Regarded as some of the smoothest coffees in the world, dark Sumatra is very popular in the American Northwest, and is a regular offering of some of the finest coffee shops. Tasting notes: Spice, Earthy.',
            price: 19.95,
            image1: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/o/r/organic-fair-trade-dark-sumatra-mandheling-beans-2021-square.jpg',
            image2: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/d/e/decaf-dark-sumatra-bag-2021-square.jpg',
            image3: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/o/r/organic-fair-trade-dark-sumatra-mandheling-beans-2021-square.jpg',
            image4: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/d/e/decaf-dark-sumatra-bag-2021-square.jpg',
        },
        {
            title: 'Italian Roast Espresso',
            describtione: 'This signature blend of Italian roasted coffee beans is a heavy, full-bodied roast. Displaying a toasty, honeyed aroma and notes of cocoa powder and smoky molasses, these gourmet beans are our most popular coffee blend. This rich & deep-bodied dark roast makes an intensely bold espresso. It also makes a killer iced coffee or a strong, full-flavored cup of joe from your standard drip machine or French Press. If you`re looking for a strong, dark brew, check this one out, hot or iced! Tasting notes: Wine, Chocolate, Nut, Spice.',
            price: 19.95,
            image1: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/i/t/italian-roast-espresso-beans-2021-square.jpg',
            image2: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/i/t/italian-roast-espresso-bag-2021-square.jpg',
            image3: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/i/t/italian-roast-espresso-beans-2021-square.jpg',
            image4: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/i/t/italian-roast-espresso-bag-2021-square.jpg',
        },
        {
            title: 'Kenya AA',
            describtione: 'On graduation day, after throwing your mortarboard into the air, you may have thought of the importance of letter grades as a thing of the past, but our Kenya AA beans prove otherwise. The AA designation is the highest grade on the scale and is based on the size, shape, and density of the beans, and after one cup, you`ll know why even an A+ wasn`t lofty enough for this coffee. Maturing in Kenya`s rich volcanic soil, these beans have a sharp, winey flavor with a distinct fruitiness that`s sure to excite the taste buds of even the most jaded coffee aficionado. The beans are roasted a bit darker than other Light coffees we offer (but not dark enough to be oily) to bring out the subtle flavor notes the normal Light roast will not. Try it, and find out why these beans are at the top of the class. Tasting notes: Citrus, Wine.',
            price: 19.95,
            image1: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/k/e/kenya-aa-beans-2021-square.jpg',
            image2: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/k/e/kenya-aa-bag-2021-square.jpg',
            image3: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/k/e/kenya-aa-beans-2021-square.jpg',
            image4: 'https://www.coffeebeandirect.com/media/catalog/product/cache/8573b5ebbd04b621bee4b931a71e7f09/k/e/kenya-aa-bag-2021-square.jpg',
        },
        {
            title: 'Millk Mug',
            describtione: 'Want to show your love and devotion to omega mart`s fresh dairy beverage? Now you can drink your daily dose of vitamin dram straight from a millk mug! Moooove over coffee cups. We`ve got the mug to match your grinning face the next time you say, “calci-yum!”. 2% homogenized culture.',
            price: 30,
            image1: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2021/02/DSC_5602.jpg',
            image2: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2021/02/DSC_5601.jpg',
            image3: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2021/02/DSC_5600-600x760.jpg',
            image4: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2021/02/DSC_5606-600x760.jpg',
        },
        {
            title: 'Travel Apple Tumbler',
            describtione: 'The freshest, fresh tumbler you`ve ever drank out of! Straight from the Source. 30 oz capacity. Removable lid. Silicone straw included. Hand wash only. Do not microwave.',
            price: 34.50,
            image1: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2021/09/DSC_4118-copy.jpg',
            image2: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2021/09/DSC_4120-copy.jpg',
            image3: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2021/09/DSC_4119-copy.jpg',
            image4: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2021/09/DSC_4118-copy.jpg',
        },
        {
            title: 'Society of Peripheral Studies Three-Handled Mug',
            describtione: 'Our coffee is fresh, local, and absolutely delicious. Enjoy our coffe in absolutely amazing mug or in our Cat Lounge. We have kitties! Big ones, small ones, fluffy ones, grumpy ones, silly ones, majestic ones, tall ones, short ones, chunky ones, dainty ones, curious ones, timid ones, grey ones, orange ones, cuddly ones, scratchy ones, old ones, young ones, brothers, sisters, mommies and kittens.',
            price: 25,
            image1: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2021/03/fullsizeoutput_1190-scaled.jpeg',
            image2: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2021/03/fullsizeoutput_11a8-scaled.jpeg',
            image3: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2021/03/fullsizeoutput_11a0-scaled.jpeg',
            image4: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2021/03/fullsizeoutput_1194-scaled.jpeg',
        },
        {
            title: 'Cat-Us Crop Top',
            describtione: '“It`s hard to blend in when clearly you are and have always been royalty.” - Fantastrophe',
            price: 35,
            image1: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2019/11/1327a970-obsidiopolisimg_5281-edited-scaled.jpg',
            image2: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2019/11/af319070-obsidiopolis_cat_us_crop_3_meow_wolf.jpg-scaled.jpg',
            image3: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2019/11/a18f38ed-obsidiopolisimg_5286-edited-scaled.jpg',
            image4: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2019/11/e83ecff4-obsidiopolisimg_5231-edited.jpg',
        },
        {
            title: 'Cat-Us Tote Bag',
            describtione: 'Be one with the plant. Uplift your spirit.',
            price: 24,
            image1: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2019/10/fbc15c95-obsidiopolisimg_5835-edited-scaled.jpg',
            image2: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2019/11/a182ae9e-obsidiopolis_cat_us_crop_tote_meow_wolf.jpg-scaled.jpg',
            image3: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2019/10/b8bc4df6-obsidiopolisimg_5843-edited-scaled.jpg',
            image4: 'https://shop.meowwolf.com/wp-content/uploads/sites/3/2019/10/fbc15c95-obsidiopolisimg_5835-edited-scaled.jpg',
        },
        {
            title: 'Cat-Us Cofee',
            describtione: 'Our coffee is fresh, local, and absolutely delicious. Enjoy our coffe in absolutely amazing mug or in our Cat Lounge. We have kitties! Big ones, small ones, fluffy ones, grumpy ones, silly ones, majestic ones, tall ones, short ones, chunky ones, dainty ones, curious ones, timid ones, grey ones, orange ones, cuddly ones, scratchy ones, old ones, young ones, brothers, sisters, mommies and kittens.',
            price: 12,
            image1: 'https://images.pexels.com/photos/350478/pexels-photo-350478.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            image2: 'https://images.pexels.com/photos/350478/pexels-photo-350478.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            image3: 'https://images.pexels.com/photos/350478/pexels-photo-350478.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
            image4: 'https://images.pexels.com/photos/350478/pexels-photo-350478.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
            title: 'Plain White Porcelain Mug and Handle',
            describtione: 'clever gift for mother, father or significant other. Sincere reactions to your thoughtfulness. Artwork for your office. Functions like any other mug while dazzling your clients and co-workers. Designed with modern lines and tapered walls, it`s surprisingly useful and comfortable to hold. Perfect for coffee lovers or tea infusers. A household accent to punctuate your home and decor.',
            price: 17.95,
            image1: 'https://m.media-amazon.com/images/I/61SU-IwyXtL._AC_SX679_.jpg',
            image2: 'https://m.media-amazon.com/images/I/81DoVMurHcL._AC_SX679_.jpg',
            image3: 'https://m.media-amazon.com/images/I/61SU-IwyXtL._AC_SX679_.jpg',
            image4: 'https://m.media-amazon.com/images/I/81DoVMurHcL._AC_SX679_.jpg',
        },
        {
            title: 'Thumbs Up Ninja Mug, Black',
            describtione: 'Included: ceramic mug - 8.5cm (diameter), removable ninja cover, samurai spoon and ninja star/shuriken coaster Ninja cover includes a pocket for the samurai spoon',
            price: 17.95,
            image1: 'https://m.media-amazon.com/images/I/41XheiJ9QoL._AC_.jpg',
            image2: 'https://m.media-amazon.com/images/I/31lD+3wFrYL._AC_.jpg',
            image3: 'https://m.media-amazon.com/images/I/31rLqWYlAvL._AC_.jpg',
            image4: 'https://m.media-amazon.com/images/I/41XheiJ9QoL._AC_.jpg',
        },
        {
            title: '250ml Handcraft Borosilicate Glass Cup Creative Cute Tea Milk Cup Coffee Glass Cup',
            describtione: 'Fantanstic creamer pitcher sports a humorous udder-shaped interior vessel. Made of high borosilicate glass of green environmental protection, crystal clear, simple sense is good. Design with double layers transparent heat resistant borosilicate glasses, perfect for coffee, tea, cappuccino, espresso or hot chocolate.',
            price: 17.95,
            image1: 'https://m.media-amazon.com/images/I/61mOgQuPQQL._AC_SX679_.jpg',
            image2: 'https://m.media-amazon.com/images/I/61Pxhb335+L._AC_SX679_.jpg',
            image3: 'https://m.media-amazon.com/images/I/615i45HQqoL._AC_SX679_.jpg',
            image4: 'https://m.media-amazon.com/images/I/417dt5dEPsL._AC_.jpg',
        },
        {
            title: 'Long-tailed tit mug',
            describtione: 'This is a mug depicting the long tailed tit design by Sandra Vick. It is one of a range of 4 designs including long tailed tits, starlings, swallows and chaffinches. Size 300 ml Dishwasher safe.',
            price: 18,
            image1: 'https://m.media-amazon.com/images/I/61Q8bAJzzEL._SX500_.jpg',
            image2: 'https://m.media-amazon.com/images/I/51PAMoDepXL._SX500_.jpg',
            image3: 'https://m.media-amazon.com/images/I/41J8adRKCxL.jpg',
            image4: 'https://m.media-amazon.com/images/I/81JqixmbIGL._SY500_.jpg',
        },
        {
            title: '3Pcs Creative Keyboard Tea Cup Keypad Ctrl Del Alt Cup Coffee Mug',
            describtione: 'VERSATILE- This bottle will look great and stylish anywhere. The gym, exercise classes, outdoor sports, daily commuting, as well as at home and in the office. Stylish colors to choose from, suitable for boys, girls, men, women, old and kids of all ages, any dress style. Design in lightweight, sleek, tough, fits most car cup holders, bottle cages and your bag.',
            price: 25.94,
            image1: 'https://m.media-amazon.com/images/I/412qdJgNVbL._AC_.jpg',
            image2: 'https://m.media-amazon.com/images/I/41NaPShmhjL._AC_.jpg',
            image3: 'https://m.media-amazon.com/images/I/41QU+ffg4lL._AC_.jpg',
            image4: 'https://m.media-amazon.com/images/I/51SPaNjNAzL._AC_.jpg',
        },
        {
            title: 'myQ Spider Cups',
            describtione: 'Ideal for personal use. Christmas present or general fun gift to someone. Ideal for all types of hot drinks - Tea, coffee, hot chocolates, latte and much more. Delicate and elegant appearance design,enjoy you tea time in the afternoon',
            price: 20.99,
            image1: 'https://m.media-amazon.com/images/I/61w4nsAQCoL._AC_SX679_.jpg',
            image2: 'https://m.media-amazon.com/images/I/41Up5i5y63L._AC_SX679_.jpg',
            image3: 'https://m.media-amazon.com/images/I/51VEFNzFDBL._AC_SX679_.jpg',
            image4: 'https://m.media-amazon.com/images/I/51m3AChwK9L._AC_SX679_.jpg',
        },
        {
            title: 'Thermic 30 cl Supremo Coffee Cups Gift Box, Pack of 2',
            describtione: 'Handmade Hot Drinks Cup. Highly Resistant to Thermal Shock. Borosilicate Double Wall. Dishwasher Safe. Photographic Gift Boxes of Two',
            price: 24.99,
            image1: 'https://m.media-amazon.com/images/I/71+zb44wBQL._AC_SX679_.jpg',
            image2: 'https://m.media-amazon.com/images/I/61xy4ZZjozL._AC_SX679_.jpg',
            image3: 'https://m.media-amazon.com/images/I/71+zb44wBQL._AC_SX679_.jpg',
            image4: 'https://m.media-amazon.com/images/I/61xy4ZZjozL._AC_SX679_.jpg',
        },
        {
            title: 'Cute Unicorn Ceramic Mug',
            describtione: 'Pink Unicorn MUG:For Unicorns Lovers , this Unicorn coffee mug is sure to get an amazing reaction, hand painted 3D Unicorn for your daughter, wife, mother or coworker on their Birthday, Christmas or Valentines. High Quality:Made of High Quality Ceramic, ECO friendly, high quality and each mug is handcrafted and goes through a strict selection process to ensure you get best one.',
            price: 11.99,
            image1: 'https://m.media-amazon.com/images/I/41mBP8z7GIL._AC_SX679_.jpg',
            image2: 'https://m.media-amazon.com/images/I/61EP9uzytOL._AC_SX679_.jpg',
            image3: 'https://m.media-amazon.com/images/I/51CPSglkyDL._AC_SX679_.jpg',
            image4: 'https://m.media-amazon.com/images/I/41mBP8z7GIL._AC_SX679_.jpg',
        },
        {
            title: 'SITAKE 2 Pack Cute Cat Ceramic Coffee Mug',
            describtione: 'Value Pack -- You will receive 1 black and 1 white cute cat pattern 450ml ceramic mugs, with 2 spoons. Besides, Each package is carefully packed to prevent accidental breakage. High Quality Material -- Made of premium ceramic, looks exquisite and cute, eco-friendly and skin-friendly, microwaves safe, much healthier and more durable than paper or plastic cups.',
            price: 15.99,
            image1: 'https://m.media-amazon.com/images/I/61L-uasZfGL._AC_SX679_.jpg',
            image2: 'https://m.media-amazon.com/images/I/61ELZlJsxrL._AC_SX679_.jpg',
            image3: 'https://m.media-amazon.com/images/I/71ripWwZzML._AC_SX679_.jpg',
            image4: 'https://m.media-amazon.com/images/I/61L-uasZfGL._AC_SX679_.jpg',
        },
        {
            title: 'Mug - Oval Pattern',
            describtione: 'White Porcelain with clear gloss interior. Dishwasher safe, do not microwave, porcelain will get very hot. Pieces are usually made to order and will ship in two weeks.',
            price: 45,
            image1: 'https://images.squarespace-cdn.com/content/v1/56b7d0fbd51cd4ba74a56129/1614197460961-QDSR31F5WKFVCKLRK8S5/061+%E2%80%94%E2%80%94+fd+-+mug+-+oval+%E2%80%94+32793.jpg?format=1000w',
            image2: 'https://images.squarespace-cdn.com/content/v1/56b7d0fbd51cd4ba74a56129/1614198449195-NTKRPLH13W2NHW7FMGC2/075+%E2%80%94%E2%80%94+fd+-+mugs+-+group+%E2%80%94+32855.jpg?format=1000w',
            image3: 'https://images.squarespace-cdn.com/content/v1/56b7d0fbd51cd4ba74a56129/1614197460961-QDSR31F5WKFVCKLRK8S5/061+%E2%80%94%E2%80%94+fd+-+mug+-+oval+%E2%80%94+32793.jpg?format=1000w',
            image4: 'https://images.squarespace-cdn.com/content/v1/56b7d0fbd51cd4ba74a56129/1614198449195-NTKRPLH13W2NHW7FMGC2/075+%E2%80%94%E2%80%94+fd+-+mugs+-+group+%E2%80%94+32855.jpg?format=1000w',
        },
    ]
}

export default getArticles;